plugins {
    id 'com.android.application'
}

android {
    namespace 'com.terpenesalad.clamwidget'
    compileSdk 35

    defaultConfig {
        applicationId 'com.terpenesalad.clamwidget'
        minSdk 26
        targetSdk 35
        versionCode((System.getenv('GITHUB_RUN_NUMBER') ?: '1') as int)
        versionName "1.0.${System.getenv('GITHUB_RUN_NUMBER') ?: '0'}"
    }

    signingConfigs {
        release {
            storeFile file('clam.keystore')
            storePassword 'clamwidget'
            keyAlias 'clam'
            keyPassword 'clamwidget'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }
}
